== Feedback

=== Feedback from Daniel B. (3rd November 2018)

* Slide 1: Great! Always nice to have an intro slide
* Slide 2: You should make this a horizontal bar chart so you can read the country labels more easily. I think making this one graph is a little confusing. I would amend to be either two charts or grouped bar charts.
* Slide 3: Same critique as before. Alternatively, you could display the difference/proportion percentage instead (what is the use rate/availability rate)
* Slide 4: This slide is good (just make it horizontal)
* Slide 5: good
* Slide 6: Excellent
* Slide 7: Great, but I would add an annotation stating your conclusion for slides 6 and 7.
* Slide 8: great
* Slide 9: excellent

=== Feedback from Dilyana B. (3rd November 2018)

Hi Jörg, nice colors and I like the bar chart.
However, I don't really understand the charts 6,7 and 8.
Maybe you could add some titles to this charts.

=== Feedback from my flat mate (3rd November 2018)

Same points as Daniel.

=== Feedback from Dilyana B. (4rd November 2018)

Nice work, Jörg!
I looked through and I noticed two points:
First: I don't understand the second slide: You’ve written: In 2012 almost, every student had access to ICT at home.
Actually, I cannot recognise this point on the chart.
It would be great if you could add any context (On which period of data do we look at).
The second point is: By scatter plot you have different points with the labels.
I am not sure if you need the colours by dots, if you have labels.
Hope it helps :)
